language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis  CI 서버의  Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  chmod +x gradlew

script: "./gradlew clean build"



# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - whthakd1207@naver.com

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p before-deploy
  - - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis rep
    secret_access_key: $AWS_SECRET_KEY
    bucket: somang-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider : codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: somang-springboot-build
    key: freelec-springboot2-webservice.zip
    bundle_type: zip
    application: somang2
    deployment_group: mimi
    region: ap-northeast-2
    wait-until-deployed: true
